### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by dparkar** [ahmetcanaydemir/react-advanced-news-ticker#5]
Getting the following error : 

> ReferenceError: regeneratorRuntime is not defined
>     at D:\src\myproject\node_modules\react-advanced-news-ticker\dist\index.js:153:50
>     at D:\src\myproject\node_modules\react-advanced-news-ticker\dist\index.js:213:6
>     at Object.<anonymous> (D:\src\myproject\node_modules\react-advanced-news-ticker\dist\index.js:442:2)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
>     at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Object.require.extensions.<computed> [as .js] (D:\src\myproject\node_modules\ts-node\src\index.ts:851:44)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
>     at Module.require (internal/modules/cjs/loader.js:974:19)
>     at require (internal/modules/cjs/helpers.js:92:18)
> wait  - compiling...
> event - compiled successfully

Found this related SO question : https://stackoverflow.com/questions/53558916/babel-7-referenceerror-regeneratorruntime-is-not-defined

I tried the following but it had no effect : 

> npm install --save core-js
> npm install --save regenerator-runtime 

Appreciate any suggestions.

**Comment by asyncjason** [comment]
Same here. Did you have any luck?

**Comment by patrickfreitasdev** [comment]
@jseparovic I was able to bypass the issue by adding this package https://www.npmjs.com/package/regenerator-runtime then const regeneratorRuntime = require("regenerator-runtime"); after use strict at the file node_modules/react-advanced-news-ticker/dist/index.js

**Comment by Hredoysen** [comment]
> @jseparovic I was able to bypass the issue by adding this package https://www.npmjs.com/package/regenerator-runtime then const regeneratorRuntime = require("regenerator-runtime"); after use strict at the file node_modules/react-advanced-news-ticker/dist/index.js

but I tried it and it says regenerator-runtime is not defined
\
